### ISSUE TITLE
Typescript Compiler failing with error TS2307

### ISSUE THREAD

**Issue by sjiwani-skillz** [pact-foundation/jest-pact#200]
The following error is thrown when running `tsc` in my project:

```
node_modules/jest-pact/dist/types.d.ts:2:53 - error TS2307: Cannot find module '@pact-foundation/pact/dsl/options' or its corresponding type declarations.

2 import { MessageConsumerOptions, PactOptions } from '@pact-foundation/pact/dsl/options';
```

The issue seems to be stemming from this line:
https://github.com/pact-foundation/jest-pact/blob/dc23a09f02d40a15c3f2b0812f0b1bc0e77bf830/src/types.ts#L5

If I change the import to be
`import { MessageConsumerOptions, PactOptions } from '@pact-foundation/pact';`  or
`import { MessageConsumerOptions, PactOptions } from '@pact-foundation/pact/src/dsl/options';`
it works.

@pact-foundation/pact - version : 9.15.5
jest-pact - version: 0.8.3

**Comment by TimothyJones** [comment]
This is fixed in jest-pact v0.9.0, releasing shortly.

I had to increase the peer dependency for pact to 9.12.2 (although that won't affect anyone experiencing this issue, because it only happens from 9.15.0 onwards, it might affect others who haven't experienced this issue yet).

Thanks for the report!
