### ISSUE TITLE
move to pact-foundation org/scope

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/jest-pact#207]
Currently this package is publishing from my personal npm account, makes sense to get it publishing under the pact-foundation

- [X] create pact-foundation org in npm

Other tasks will be picked up under https://github.com/pact-foundation/jest-pact/issues/208 for the move to GH actions

**Comment by YOU54F** [comment]
![Screenshot 2022-03-17 at 20 40 51](https://user-images.githubusercontent.com/19932401/158891584-f4239115-02a7-4f6c-bf1b-dbd36cea1f55.png)

Looks like its already under the pact-foundation org in npm, but not scoped. 

If we do scope, we may want to do the same with https://github.com/pact-foundation/mocha-pact

Thoughts anyone?

**Comment by TimothyJones** [comment]
I think pact-foundation is still just an npm user- there isn’t actually an org. It would be worth converting it to an org, since it’s not really a person.

**Comment by YOU54F** [comment]
Agreed! Looks like it's easy enough to do as well 

https://docs.npmjs.com/converting-your-user-account-to-an-organization

What are your thoughts on moving to a `@pact-foundation` scope?

**Comment by YOU54F** [comment]
> Agreed! Looks like it's easy enough to do as well
> 
> https://docs.npmjs.com/converting-your-user-account-to-an-organization


I’ll get a canny roadmap ticket up to track this, as there will actually be a few tasks to consider and it’s worth taking the time to flesh them out

**Comment by TimothyJones** [comment]
> What are your thoughts on moving to a @pact-foundation scope?

I previously intentionally didn't do this, so that it would sort with other jest-related packages in `package.json`. My thinking was that it's idomatic for jest plugins / extensions to be `jest-*`, and it's likely that someone migrating away from Jest would want to keep pact. I don't feel strongly about it though.

For me, the arguments are:

* Consistency with Jest extensions is reasonable, so `jest-pact` is an appropriate name
* Consistency with other pact npm packages is also reasonable, so `@pact-foundation/jest-pact` is an appropriate name (although maybe `@pact-foundation/jest-extensions` is better - since pact is already in the name?)

I don't feel strongly.

I think that churning on the name will inconvenience some users, and doing it just so that it's under `@pact-foundation` isn't necessarily worth that pain.

I do think it's worth releasing a v1, since the interface is now pretty stable.
